-- Growth CRM performance must be driven by real workflow events, not a
-- combined pipeline-stage label. This column records which agent performed
-- the explicit funding-application submission action. Existing timestamps
-- intentionally remain unattributed and therefore do not count: they were
-- previously generated by a stage change and cannot prove a submission.
alter table public.crm_opportunities
  add column if not exists application_submitted_by uuid references public.crm_users(id) on delete set null;

comment on column public.crm_opportunities.application_submitted_by is
  'Agent credited when a Business Financing application is explicitly marked submitted; null legacy stage-derived timestamps are not reportable.';

-- proposal_sent_at is retained for backwards-compatible reads and existing
-- deployments, but performance now comes from crm_lead_emails.delivered_at.
comment on column public.crm_opportunities.proposal_sent_at is
  'Legacy stage-derived value. Do not use for performance; confirmed deliveries in crm_lead_emails are the source of truth.';

-- Preserve the old frozen ledger for audit purposes while allowing each
-- completed period to be recomputed once under the verified-event model.
alter table public.crm_agent_biweekly_performance
  add column if not exists definition_version integer;

update public.crm_agent_biweekly_performance
set definition_version = 1
where definition_version is null;

alter table public.crm_agent_biweekly_performance
  alter column definition_version set default 2,
  alter column definition_version set not null,
  drop constraint if exists crm_agent_biweekly_performance_unique;

alter table public.crm_agent_biweekly_performance
  add constraint crm_agent_biweekly_performance_unique
  unique (agent_id, period_start, definition_version);

comment on column public.crm_agent_biweekly_performance.definition_version is
  '1 = legacy stage-derived metrics; 2 = verified workflow-event metrics.';
